const escapePdf = (s) =>
  String(s)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

class PdfPage {
  constructor(width = 595, height = 842) {
    this.width = width;
    this.height = height;
    this.ops = [];
  }

  text(str, x, y, { size = 10, bold = false, color = null } = {}) {
    const key = bold ? "F2" : "F1";
    const colorOp = color ? `${color[0]} ${color[1]} ${color[2]} rg ` : "";
    this.ops.push(`${colorOp}BT /${key} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${escapePdf(str)}) Tj ET`);
  }

  rule(x1, y1, x2, y2, color = [0.82, 0.87, 0.93]) {
    this.ops.push(`${color[0]} ${color[1]} ${color[2]} RG 0.75 w ${x1} ${y1} m ${x2} ${y2} l S`);
  }

  bar(x, y, w, h, color = [0.09, 0.47, 0.95]) {
    this.ops.push(`${color[0]} ${color[1]} ${color[2]} rg ${x} ${y} ${w} ${h} re f`);
  }

  content() {
    return this.ops.join("\n");
  }
}

const buildBlob = (page) => {
  const contentStream = page.content();
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${page.width} ${page.height}] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>`,
    `<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [];
  objects.forEach((obj, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
};

const STATUS_LABELS = {
  PAID: "Paid",
  PARTIALLY_PAID: "Partially Paid",
  UNPAID: "Unpaid",
};

const formatMoney = (value) =>
  Number(value || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

const formatDateTime = (value) =>
  new Date(value).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

export function downloadReceiptPdf(receipt) {
  const page = new PdfPage();
  const W = page.width;
  const margin = 48;
  const labelX = margin;
  const valueX = margin + 190;
  let y = page.height - 120;

  page.bar(margin, page.height - 98, W - margin * 2, 6);
  y -= 20;
  page.text("PAYMENT RECEIPT", W / 2, y, { size: 20, bold: true });
  y -= 22;
  page.text("Campus Ride Sharing", W / 2, y, { size: 10 });
  y -= 12;
  page.text("Payment tracker receipt", W / 2, y, { size: 9, color: [0.45, 0.52, 0.6] });
  y -= 30;
  page.rule(margin, y, W - margin, y);

  const row = (label, value) => {
    y -= 26;
    page.text(label, labelX, y, { size: 9.5, color: [0.42, 0.48, 0.56] });
    page.text(value, valueX, y, { size: 9.5 });
  };

  y -= 10;
  row("Request ID", receipt.requestCode || "-");
  row("Requester", receipt.requester?.name || "-");
  row("Payer", receipt.payer?.name || "-");
  row("Amount Paid", `BDT ${formatMoney(receipt.amount)}`);
  row(
    "Payment Method",
    receipt.method === "BKASH" ? "bKash (Online Payment)" : "Manual / Offline"
  );
  row("Transaction / Reference ID", receipt.reference || "-");
  row("Date & Time", formatDateTime(receipt.paidAt || Date.now()));

  y -= 24;
  page.rule(margin, y, W - margin, y);

  const summary = receipt.summary || {};
  y -= 12;
  page.text("PAYMENT SUMMARY", labelX, y, { size: 11, bold: true });
  row("Amount Due", `BDT ${formatMoney(summary.amountDue)}`);
  row("Amount Paid", `BDT ${formatMoney(summary.amountPaid)}`);
  row("Remaining Balance", `BDT ${formatMoney(summary.remaining)}`);
  row("Status", STATUS_LABELS[summary.status] || summary.status || "-");

  y -= 34;
  page.rule(margin, y, W - margin, y);
  y -= 24;
  page.text("Thank you. This receipt was generated by Campus Ride Sharing.", labelX, y, {
    size: 9,
    color: [0.45, 0.52, 0.6],
  });

  const url = URL.createObjectURL(buildBlob(page));
  const a = document.createElement("a");
  a.href = url;
  a.download = `receipt-${receipt.requestCode || "payment"}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
